server:
  port: 8083

spring:
  application:
    name: aircraft-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:aircraft_db}?stringtype=unspecified
    username: ${DB_USERNAME:aircraft_user}
    password: ${DB_PASSWORD:aircraft_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    web:
      pageable:
        max-page-size: ${MAX_PAGE_SIZE:50}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - ru.hls.aircraft_service.config.FeignClientException
    instances:
      userService:
        baseConfig: default
