server:
  port: 8082
spring:
  application:
    name: deal-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:deal_db}
    username: ${DB_USERNAME:deal_user}
    password: ${DB_PASSWORD:deal_pass}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    web:
      pageable:
        max-page-size: ${MAX_PAGE_SIZE:50}