server:
  port: 8081

spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:user_db}
    username: ${DB_USERNAME:user_user}
    password: ${DB_PASSWORD:user_pass}
    driver-class-name: org.postgresql.Driver

  # used only for Liquibase migrations
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:user_db}
    username: ${DB_USERNAME:user_user}
    password: ${DB_PASSWORD:user_pass}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:user_db}
    user: ${DB_USERNAME:user_user}
    password: ${DB_PASSWORD:user_pass}

